### ISSUE TITLE
blob.data not returning the binary data of the blob

### ISSUE THREAD

**Issue by levinotik** [mojombo/grit#105]
Might be missing something basic here, but....

When I try:

```
repo = Repo.new("public/git")
fname = 'snippet'
File.open("public/git/myrepo.git/#{fname}", 'w') {|f| f.puts("hello grit!")}
Dir.chdir("public/git/myrepo.git") {repo.add(fname)}
repo.commit_index 'my amazing commit'   

ids = repo.commits.map {|c| c.id}

ids.each do |id| 
  logger.info repo.blob(id).data
end
```

 For each call to repo.blob(id).data, the logger prints what looks like the git log, instead of the data of the blob:

tree 2cf5d81a9de38f7a0f6b4f8bba0228183247ccb9
parent 69adca1f16150ea7d7cac0774a9c03bbcbc49a92
author Levi Notik levinotik@gmail.com 1330706648 -0500
committer Levi Notik levinotik@gmail.com 1330706648 -0500

my amazing commit

**Comment by technoweenie** [comment]
That's because you're reading commit SHAs, not blob SHAs.  [Grit::Repo#blob](https://github.com/mojombo/grit/blob/master/lib/grit/repo.rb#L536) takes a blob SHA, and runs [cat-file -p](https://github.com/mojombo/grit/blob/master/lib/grit/blob.rb#L43) on it.

**Comment by technoweenie** [comment]
Pro Grit has a great chapter on [git internals](http://progit.org/book/ch9-2.html) that you should check out if you haven't.

**Comment by levinotik** [comment]
Thanks @technoweenie. So what's the right way to get the blob SHAs? ;)

**Comment by levinotik** [comment]
@technoweenie oh i get it. I gotta use the tree. like: 

 tree = Tree.construct(repo, 'master')
 data = tree.blobs.map {|b| repo.blob(b.id).data}
