### ISSUE TITLE
Bump version and release on Rubygems?

### ISSUE THREAD

**Issue by runemadsen** [mojombo/grit#107]
It would be great if you could release the latest code to rubygems, so we can take advantage of tag creation, etc in our custom gems.

**Comment by khustochka** [comment]
+1

I would appreciate a release (be it pre, or beta) because current master works on Windows (due to posix-spawn), and 2.4.1 fails.

**Comment by nathanvda** [comment]
Version 2.5.0 was released on 22nd of april, so I don't think this issue is still relevant?

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
