### ISSUE TITLE
Close opened files

### ISSUE THREAD

**Issue by rtomayko** [mojombo/grit#11]
There's a few places where we're opening files but not closing them, relying on finalization or process exit to clean things up. In some cases, this is causes minute delays in unmounting filesystems. Here's a patch that makes sure files are closed immediately when no longer needed:

http://github.com/rtomayko/grit/compare/upstream...closefiles

I've already applied this to our vendor'd grit, btw.

**Comment by defunkt** [comment]
Merged into master.
