### ISSUE TITLE
posix-spawn does not work in jruby

### ISSUE THREAD

**Issue by gamemachine** [mojombo/grit#110]
grit 2.5.0 does not work with jruby because posix-spawn does not work with jruby.

There is a minimal jruby gem that provides spawn.

https://github.com/headius/spoon

Chris

**Comment by tmm1** [comment]
posix-spawn supports jruby. What issue are you seeing?

**Comment by gamemachine** [comment]
LoadError: load error: posix_spawn_ext -- java.lang.UnsatisfiedLinkError: failed to load shim library, error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/marvel/.rvm/rubies/jruby-1.6.7/lib/native/x86_64-Linux/libjruby-cext.so)
           require at org/jruby/RubyKernel.java:1033
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:639
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
            (root) at /home/marvel/.rvm/gems/jruby-1.6.7/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:2
           require at org/jruby/RubyKernel.java:1033
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:639
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
            (root) at /home/marvel/.rvm/gems/jruby-1.6.7/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:1
           require at org/jruby/RubyKernel.java:1033
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:639
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
            (root) at /home/marvel/.rvm/gems/jruby-1.6.7/gems/posix-spawn-0.3.6/lib/posix-spawn.rb:2
           require at org/jruby/RubyKernel.java:1033
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:640
  new_constants_in at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:639
   load_dependency at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:223
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/activesupport-3.1.4/lib/active_support/dependencies.rb:240
            (root) at /home/marvel/.rvm/gems/jruby-1.6.7/gems/grit-2.5.0/lib/grit/git.rb:34
           require at org/jruby/RubyKernel.java:1033
           require at /home/marvel/.rvm/gems/jruby-1.6.7/gems/grit-2.5.0/lib/grit.rb:68

**Comment by tmm1** [comment]
This looks like a jruby bug. Maybe something is screwy with your installation, but posix-spawn has no control over `jruby-1.6.7/lib/native/x86_64-Linux/libjruby-cext.so`

**Comment by trunda** [comment]
Hi, same issue here

LoadError: load error: posix_spawn_ext -- java.lang.UnsatisfiedLinkError: failed to load shim library, error: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /home/vagrant/jruby-1.6.7.2/lib/native/i386-Linux/libjruby-cext.so)
  require at org/jruby/RubyKernel.java:1033
   (root) at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:2
  require at org/jruby/RubyKernel.java:1033
   (root) at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:1
  require at org/jruby/RubyKernel.java:1033
   (root) at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/posix-spawn-0.3.6/lib/posix-spawn.rb:2
  require at org/jruby/RubyKernel.java:1033
   (root) at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/grit-2.5.0/lib/grit/git.rb:34
  require at org/jruby/RubyKernel.java:1033
  require at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/grit-2.5.0/lib/grit.rb:68
     each at org/jruby/RubyArray.java:1615
  require at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/bundler-1.2.0/lib/bundler/runtime.rb:66
     each at org/jruby/RubyArray.java:1615
  require at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/bundler-1.2.0/lib/bundler/runtime.rb:55
  require at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/bundler-1.2.0/lib/bundler.rb:128
   (root) at /vagrant/config/application.rb:7
  require at org/jruby/RubyKernel.java:1033
   (root) at /vagrant/config/application.rb:53
      tap at org/jruby/RubyKernel.java:1787
   (root) at /home/vagrant/jruby-1.6.7.2/lib/ruby/gems/1.8/gems/railties-3.2.6/lib/rails/commands.rb:50
  require at org/jruby/RubyKernel.java:1033
   (root) at script/rails:6

**Comment by TylerBrock** [comment]
Yup, I'm having the same problem.

**Comment by mbrinkme** [comment]
me too! 

student@ub12:~/c$ rails s
LoadError: load error: posix_spawn_ext -- java.lang.UnsatisfiedLinkError: failed to load shim library, error: /home/student/.rvm/rubies/jruby-1.7.2/lib/native/i386-Linux/libjruby-cext.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
  require at org/jruby/RubyKernel.java:1027
   (root) at /home/student/.rvm/gems/jruby-1.7.2/gems/posix-spawn-0.3.6/lib/posix/spawn.rb:2
  require at org/jruby/RubyKernel.java:1027
   (root) at /home/student/.rvm/gems/jruby-1.7.2/gems/pygments.rb-0.4.2/lib/pygments/popen.rb:1
  require at org/jruby/RubyKernel.java:1027
   (root) at /home/student/.rvm/gems/jruby-1.7.2/gems/pygments.rb-0.4.2/lib/pygments/popen.rb:2
  require at org/jruby/RubyKernel.java:1027
   (root) at /home/student/.rvm/gems/jruby-1.7.2/gems/pygments.rb-0.4.2/lib/pygments.rb:1
     each at org/jruby/RubyArray.java:1613
   (root) at /home/student/.rvm/gems/jruby-1.7.2/gems/pygments.rb-0.4.2/lib/pygments.rb:1
     each at org/jruby/RubyArray.java:1613
   (root) at /home/student/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:1
  require at /home/student/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:72
  require at /home/student/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:70
  require at org/jruby/RubyKernel.java:1027
  require at /home/student/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.3.4/lib/bundler/runtime.rb:59
      tap at org/jruby/RubyKernel.java:1754
  require at /home/student/.rvm/gems/jruby-1.7.2@global/gems/bundler-1.3.4/lib/bundler.rb:132
  require at org/jruby/RubyKernel.java:1027
   (root) at script/rails:6
student@ub12:~/c$
