### ISSUE TITLE
.git/description missing on server

### ISSUE THREAD

**Issue by sanders** [mojombo/grit#14]
A newly cloned grit has a failing test out of the box because the server doesn't have the description file set.  A work around is to copy test/dot_git/description to .git/description

I think just adding the description to the repo on github would solve the problem (might have to delete the repo and recreate from someone's local copy).

1) Error:
test_description(TestRepo):
Errno::ENOENT: No such file or directory - /Users/brandon/Code/grit/.git/description

**Comment by bobbywilson0** [comment]
I believe this is now fixed, I justed tested a newly cloned grit and didn't receive this error. Please consider closing this issue.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
