### ISSUE TITLE
NoMethodError when dealing with a GPG signed commit

### ISSUE THREAD

**Issue by alexdo** [mojombo/grit#141]
Hey there!

I encountered a problem with signed commits.
This is the output of Sinatra I got from running Gollum: https://gist.github.com/3501696
_(The same on OS X 10.8.1 + Debian 6.0.4; both running Ruby 1.9.3-p194 and Gollum 2.1.7)_

I set up a repository that reproduces the issue. The most recent commit is signed. Fire up gollum aaaand - it breaks.
https://github.com/alexdo/gollum-gpg-test

This issue was already discussed within gollums issues: https://github.com/github/gollum/issues/493
Any chance of getting it fixed?

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
