### ISSUE TITLE
Grit doesn't correctly identify renames

### ISSUE THREAD

**Issue by dekimsey** [mojombo/grit#148]
Git commit objects have a diff attribute, these diff objects have a rename property. They are not currently initialized correctly based on the log processing logic in `Commit.list_from_string`.

Given a a repository with two commits, one to create a file and one to rename it. Grit's log processing function `Commit.list_from_string` does not recognize renames. It would appear that the default logging output format of [`{ :format => 'raw'}`](https://github.com/mojombo/grit/blob/master/lib/grit/repo.rb#L542) does not provide sufficient information. It should instead be using the `--raw` option. 
#### `git log --pretty=raw Home.md`

No information about renames provided here.

```
commit 08578d49435214faee948d41ad13499e7f866627
tree e9c20987e7f6f0a74fcfc2436e5cb0adb06483ab
parent 66111fca12fe09ff6069677f33db4294103072bf
author Daniel Kimsey <dekimsey@ufl.edu> 1352320593 -0500
committer Daniel Kimsey <dekimsey@ufl.edu> 1352320593 -0500

    Renamed README.md to Home.md for Gollum

```
#### `git log --raw Home.md`

Rename information is incomplete, looks like it was a newly created file. This makes sense.

```
commit 08578d49435214faee948d41ad13499e7f866627
Author: Daniel Kimsey <dekimsey@ufl.edu>
Date:   Wed Nov 7 15:36:33 2012 -0500

    Renamed README.md to Home.md for Gollum

:000000 100644 0000000... e34318b... A  Home.md
```
#### `git log --pretty=raw --follow Home.md`

Enabling `--follow` doesn't show renames still.

```
commit 08578d49435214faee948d41ad13499e7f866627
tree e9c20987e7f6f0a74fcfc2436e5cb0adb06483ab
parent 66111fca12fe09ff6069677f33db4294103072bf
author Daniel Kimsey <dekimsey@ufl.edu> 1352320593 -0500
committer Daniel Kimsey <dekimsey@ufl.edu> 1352320593 -0500

    Renamed README.md to Home.md for Gollum

commit 66111fca12fe09ff6069677f33db4294103072bf
tree a242caa19b4cfde393978d7e5593ce3251aa943c
author Daniel Kimsey <dekimsey@ufl.edu> 1352320565 -0500
committer Daniel Kimsey <dekimsey@ufl.edu> 1352320565 -0500

    Initial commit
```
#### `git log --raw --follow Home.md`

Now we see the correct data. The `R100` seems to be Git's % confidence in the rename.

```
commit 08578d49435214faee948d41ad13499e7f866627
Author: Daniel Kimsey <dekimsey@ufl.edu>
Date:   Wed Nov 7 15:36:33 2012 -0500

    Renamed README.md to Home.md for Gollum

:100644 100644 e34318b... e34318b... R100       README.md       Home.md

commit 66111fca12fe09ff6069677f33db4294103072bf
Author: Daniel Kimsey <dekimsey@ufl.edu>
Date:   Wed Nov 7 15:36:05 2012 -0500

    Initial commit

:000000 100644 0000000... e34318b... A  README.md
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
