### ISSUE TITLE
update_ref is not atomic

### ISSUE THREAD

**Issue by candlerb** [mojombo/grit#15]
update_ref and commit don't support (new_value, old_value) like the C git. This means it's not safe against overlapping commits by concurrent processes. Contrived example:

> > r1 = Grit::Repo.new(".")
> > => #<Grit::Repo "/home/candlerb/tmp/tst1.git">
> > i1 = r1.index
> > => #<Grit::Index:0xb7001204 @current_tree=nil, @repo=#<Grit::Repo "/home/candlerb/tmp/tst1.git">, @tree={}>
> > candlerb@candlerb-desktop:tst1.git$ irb --simple-prompt -rubygems -rgrit
> > r1 = Grit::Repo.new(".")
> > => #<Grit::Repo "/home/candlerb/tmp/tst1.git">
> > i1 = r1.index
> > => #<Grit::Index:0xb70051d8 @current_tree=nil, @repo=#<Grit::Repo "/home/candlerb/tmp/tst1.git">, @tree={}>
> > i1.add("foo","aaa")
> > => "aaa"
> > i1.commit("Initial commit")
> > => "a93019e0310492c8854c4b5e16d8f961ab16afff"
> > h = r1.head.commit
> > => "a93019e0310492c8854c4b5e16d8f961ab16afff"
> > i1 = r1.index
> > => #<Grit::Index:0xb6ff6a98 @current_tree=nil, @repo=#<Grit::Repo "/home/candlerb/tmp/tst1.git">, @tree={}>
> > i1.add("foo","bbb")
> > => "bbb"
#### Now say a concurrent commit takes place

> > r2 = Grit::Repo.new(".")
> > => #<Grit::Repo "/home/candlerb/tmp/tst1.git">
> > i2 = r2.index
> > => #<Grit::Index:0xb6fee424 @current_tree=nil, @repo=#<Grit::Repo "/home/candlerb/tmp/tst1.git">, @tree={}>
> > i2.add("foo","ccc")
> > => "ccc"
> > i2.commit("Commit two", [h])
> > => "ac0e8461589b39738974f758d508e238d64fa9dd"
> > i1.commit("Conflicting commit", [h])
> > => "f36d24ea4d820a9c109e35b22c8a77fed2060dcb"
#### One of the commits is silently lost

$ git log
commit f36d24ea4d820a9c109e35b22c8a77fed2060dcb
Author: Brian Candler b.candler@pobox.com
Date:   Mon Mar 22 05:11:20 2010 -0700

```
Conflicting commit
```

commit a93019e0310492c8854c4b5e16d8f961ab16afff
Author: Brian Candler b.candler@pobox.com
Date:   Mon Mar 22 05:10:00 2010 -0700

```
Initial commit
```

Suggested behaviour: update_ref and commit to take an (optional) 'previous head' value. Implement locking in update_ref, and if the previous head doesn't match, raise an exception.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
