### ISSUE TITLE
init_bare ignores errors from git-init

### ISSUE THREAD

**Issue by candlerb** [mojombo/grit#17]
init_bare appears to succeed, even when it doesn't.

> > Dir.mkdir("tst3.git")
> > => 0
> > r = Grit::Repo.init_bare("tst3.git")
> > => #<Grit::Repo "/home/candlerb/tmp/tst3.git">
> > Dir["tst3.git/*"]
> > => []
> > Dir["tst3.git/.git"]
> > => []

This is on an Ubuntu Hardy system with git-1.5.5.1, and I'm pretty sure it fails because git-init doesn't have the --bare option. But no error is raised.

$ git --version
git version 1.5.5.1
$ git-init --bare
usage: git-init [-q | --quiet] [--template=<template-directory>] [--shared]
$ echo $?
129

**Comment by bobbywilson0** [comment]
The core problem is related to #2 basically says grit doesn't return non-zero exit codes properly

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
