### ISSUE TITLE
Load repo upwards in specified path

### ISSUE THREAD

**Issue by jessicalevine** [mojombo/grit#172]
This is a feature request, and if I have time I may take a crack at a pull-request. I haven't thought deeply into the feasibility, but being able to require a path, or even a filepath, and have it check up the directories in the path for a ".git" folder to require would be awesome. I'd love to hear the creator/communities thoughts before I try to implement it.

**Comment by nickserv** [comment]
This pull request might have what you're looking for: #178

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
