### ISSUE TITLE
No method error in loop.rb

### ISSUE THREAD

**Issue by trans** [mojombo/grit#173]
Getting an error on this line:

https://github.com/mojombo/grit/blob/v2.5.0/lib/grit/git-ruby/internal/loose.rb#L108

The error reported by Sinatra is

```
NoMethodError at /
undefined method `>>' for "x":String

file: loose.rb
location: unpack_object_header_gently
line: 108
```

**Comment by trans** [comment]
I've now learned a good bit about this problem reading other issue reports. The problem has do with changes made in Ruby 2.0. The styx/grit fork looks to have the fix. Please merge the styx fork and release a new version of grit. If you do not have the time to do so, please delegate the task to someone else. I am sure there would be enough volunteers.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
