### ISSUE TITLE
2.0 Support?

### ISSUE THREAD

**Issue by covard** [mojombo/grit#176]
I see a lot of issues and requests for Ruby 2.0. I am wondering if these will be implemented. I have a client that has a requirement that I use the grit gem but also Ruby 2.0 is a requirement. Appreciate any reply.
Thanks,
Curtis

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
