### ISSUE TITLE
Difficult to get tree sha1 from repo/head

### ISSUE THREAD

**Issue by candlerb** [mojombo/grit#18]
Consider the following code, where you want to avoid a commit if the tree is unchanged:

```
repo = Grit::Repo.new(param("repo_path"))
index = repo.index
index.add("some path", "some data")  # might be identical to existing data
index.commit("Backed up config", [repo.head.commit], nil, XXXX)
```

What goes into XXXX to prevent the commit taking place if the trees are identical? So far the best I can do is:

```
(repo.commit(repo.head.commit).tree.id rescue nil))
```

which isn't particularly neat. Should repo.head.commit return a commit object, rather than just the sha1?

Note that Commit#to_s gives to sha1 already, so having an array of Commit objects already works for the 'parents' argument.

**Comment by igorw** [comment]
Basically the same as issue5: http://github.com/mojombo/grit/issues#issue/5

**Comment by igorw** [comment]
I have a fix for this: http://github.com/evil3/grit/compare/master...issue5

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
