### ISSUE TITLE
Tree#to_s to give sha1?

### ISSUE THREAD

**Issue by candlerb** [mojombo/grit#19]
> > repo.commits[0]
> > => #<Grit::Commit "f36d24ea4d820a9c109e35b22c8a77fed2060dcb">
> > repo.commits[0].to_s
> > => "f36d24ea4d820a9c109e35b22c8a77fed2060dcb"
> > repo.commits[0].tree
> > => #<Grit::Tree "020d33c4870e05e6ba96726da154c822d08750ed">
> > repo.commits[0].tree.to_s
> > => "#Grit::Tree:0xb6fe8998"

For consistency and convenience, I suggest the last line could give the tree sha1 string instead.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
