### ISSUE TITLE
Added Grit::Repo#recent_tag_name

### ISSUE THREAD

**Issue by technoweenie** [mojombo/grit#20]
See the tag_annotation branch on [technoweenie/grit](http://github.com/technoweenie/grit/tree/tag_annotation). 

http://github.com/technoweenie/grit/blob/tag_annotation/lib/grit/repo.rb#L135-157

**Comment by binki** [comment]
those URLs lead to 404s...

**Comment by technoweenie** [comment]
That's because it was merged :)
