### ISSUE TITLE
Implemented Repo.init

### ISSUE THREAD

**Issue by GramGibson** [mojombo/grit#23]
Please see this branch:
http://github.com/GramGibson/grit/tree/repo-init
(specifically GramGibson/grit@5c47a212950ae6e92b5240c9b796861b904300d1)

I implemented the Repo.init method as per the TODO item. Repos can be initialized like:
Grit::Repo.init('/var/git/mynewrepo')

**Comment by bobbywilson0** [comment]
I went to look over what you have done and it appears you have removed your grit fork. Please consider closing this issue since the code isn't there anymore.
