### ISSUE TITLE
1.9 Encoding Issue

### ISSUE THREAD

**Issue by cehoffman** [mojombo/grit#24]
I was trying to use the new Gollum project recently on 1.9 and ran into an encoding issue inside of Grit. Digging into it the fix was rather simple and I made a topic branch [here](http://github.com/op4g/grit/commits/1.9_compat).

**Comment by stephencelis** [comment]
+1

Tested in 1.9.2 where Grit::Repo#commits had been raising `ArgumentError: invalid byte sequence in UTF-8`.

**Comment by antage** [comment]
Similar error in 1.9.2 (String#getord): http://github.com/github/gollum/issues#issue/17

**Comment by dstrelau** [comment]
+1 Fixes isuses with gollum.

**Comment by postmodern** [comment]
When can we have a release that fixes this?

**Comment by antage** [comment]
grit 2.2.0 + gollum 1.0.1 have same bug:

```
ArgumentError - invalid byte sequence in UTF-8:
 /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.2.0/lib/grit/ruby1.9.rb:3:in `ord'
 /opt/ruby-1.9.2/lib/ruby/gems/1.9.1/gems/grit-2.2.0/lib/grit/ruby1.9.rb:3:in `getord'
```

**Comment by stephencelis** [comment]
While the topic branch has been applied and the general encoding issue fixed, an additional encoding issue exists when attempting to commit a blob with a UTF-8-encoded name.

```
index.add "Café", "blah"
index.commit "message", nil, actor, tree
```

Results in:

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
 grit (2.3.0) lib/grit/index.rb:137:in `%'
 grit (2.3.0) lib/grit/index.rb:137:in `block in write_tree'
 grit (2.3.0) lib/grit/index.rb:132:in `each'
 grit (2.3.0) lib/grit/index.rb:132:in `write_tree'
 grit (2.3.0) lib/grit/index.rb:80:in `commit'
```

I've fixed this in my app by forcing the encoding of my string, beforehand, to `ASCII-8BIT`, and monkey-patching `Grit::GitRuby::Internal::LooseStorage#get_raw_object` to try `content.force_encoding 'UTF-8'` if content.length != size`, but I assume the library-specific fix shouldn't be so 1.9-heavy.

**Comment by hiroshi** [comment]
FYI, I'v just send a pull request, fixing one of ruby 1.9 encoding problem.

https://github.com/mojombo/grit/pull/51

**Comment by Dahie** [comment]
For the record, I'm having the same problem as stephencelis. I'm using version 2.4.1 of grit. Is there a solution in the works for this?

**Comment by brodock** [comment]
We are experiencing the same type of problem with Gitlab, and I've a alternative that may help fix this issue, as commented here: https://github.com/gitlabhq/gitlabhq/issues/725

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
