### ISSUE TITLE
Gemspec has wrong homepage listed

### ISSUE THREAD

**Issue by itspriddle** [mojombo/grit#25]
The gemspec in master lists http://github.com/github/gollum as the homepage, so the URL on [RubyGems / grit](http://rubygems.org/gems/grit) points to the wrong page.

Here's a patch: [99d1e240@itspriddle/grit](http://github.com/itspriddle/grit/commit/99d1e240f779b560a7ce4bbe817c3bb4dc1733bf)

**Comment by mojombo** [comment]
Merged.
