### ISSUE TITLE
How can I get remote repository with grit?

### ISSUE THREAD

**Issue by sjoonk** [mojombo/grit#28]
Is there any way to get the remote git repository with Grit::Repo ?
Please let me know if any. thanks.

**Comment by Vanuan** [comment]
+1 for that feature

**Comment by gorenje** [comment]
have you seen Git::Repo#remote_list --> that gives you the names of the remotes but no url information.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
