### ISSUE TITLE
Need to set --work-tree

### ISSUE THREAD

**Issue by ConradIrwin** [mojombo/grit#3]
In addition to --git-dir, otherwise the current working tree will be used (if a .git directory is present, even if the --git-dir points elsewhere)

**Comment by davetron5000** [comment]
I have a fix for this (I think; I was having this problem, too, and this fix works)

http://github.com/davetron5000/grit/tree/add-work-tree

**Comment by ghost** [comment]
this is already in the smoke branch

**Comment by davetron5000** [comment]
Yup, I think my patch was added

**Comment by ghost** [comment]
it got reverted, as it broke github in some way. would be nice to get it in again

**Comment by lambda** [comment]
I ran into this problem, and have fixed it in lambda@2736d20753fe8eb3c49cdd3c55821c5701182bed; I've submitted a [pull request](https://github.com/mojombo/grit/pull/43), so hopefully that will get reviewed and applied, or sent back to me to improve and re-submit.

**Comment by vrinek** [comment]
+1

**Comment by nand2** [comment]
+1

**Comment by nand2** [comment]
For info, I'm using this workaround:

```
mypath = '/xx/xx'
repo = Grit::Repo.new(mypath)
[..]
repo.git.reset({:env => {'GIT_WORK_TREE' => mypath}, :hard => true}, commit_id)
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
