### ISSUE TITLE
Git pull and reset

### ISSUE THREAD

**Issue by morgoth** [mojombo/grit#31]
I cannot find how to do: git reset (hard) and git pull.
There are examples in API.txt, like Git#reset_hard, but this method doesn't exist.
Currently I am using gem git (where those methods are implemented),
Are they really missing in grit gem?

**Comment by morgoth** [comment]
Any feed on this issue?

**Comment by jeffWelling** [comment]
Really? No feedback _at all_?
This is disheartening. It's looking like the "deprecated" git gem is actually more functional than the 'grit' gem, at least in some aspects.  I'm not so much concerned with speed as I am with functionality.

It would be nice to at least see some kind of acknowledgment, but I guess the authors are too busy for even that. :(

**Comment by RLovelett** [comment]
Was anything ever added to this?

**Comment by wingrunr21** [comment]
Git#reset_hard won't work the way grit is currently written.  Grit uses method_missing to support those missing commands.  See https://github.com/mojombo/grit/blob/master/lib/grit/git.rb#L313

Anyway, to answer your question:

```
g = Grit::Repo.new('/path/to/git/repo')
g.git.reset({:hard => true}, 'HEAD')
g.git.pull({}, "origin", "master")
```

**Comment by RyanScottLewis** [comment]
Any work on this? `Grit::Repo#pull` doesn't seem too far fetched to me.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).

**Comment by eremite** [comment]
Estimated Time: 3h 42m; Actual Time: 47m 13s :clap:

**Comment by eremite** [comment]
Estimated Time: 3h 42m; Actual Time: 47m 13s :smiley:
