### ISSUE TITLE
test_tag.rb 's ordering of tags disagrees with git(1).

### ISSUE THREAD

**Issue by binki** [mojombo/grit#34]
1) Failure:
test_list_from_string(TestTag)
    [./test/test_tag.rb:19:in `test_list_from_string'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<"not_annotated"> expected but was
<"annotated">.

  2) Failure:
test_list_from_string_for_annotated_tag(TestTag)
    [./test/test_tag.rb:37:in `test_list_from_string_for_annotated_tag'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<"annotated"> expected but was
<"not_annotated">.

  3) Failure:
test_reads_annotated_tag_contents(TestTag)
    [./test/test_tag.rb:93:in `test_reads_annotated_tag_contents'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<"annotated"> expected but was
<"not_annotated">.

  4) Failure:
test_reads_light_tag_contents(TestTag)
    [./test/test_tag.rb:81:in `test_reads_light_tag_contents'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in`**send**'
     /usr/lib64/ruby/gems/1.8/gems/mocha-0.9.8/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb:19:in `run']:
<"not_annotated"> expected but was
<"annotated">.

190 tests, 436 assertions, 4 failures, 0 errors

ohnobinki@ohnopublishing ~/grit2 $ git --git-dir=test/dot_git tag
annotated
not_annotated
packed
packed_annotated
v0.7.0

The test's codes suggests that there is some reason for git to always output 'not_annotated' before it outputs 'annotated'.

**Comment by binki** [comment]
Actually, I guess this is what needs to be noted:
irb(main):022:0> files = Dir.glob('/home/ohnobinki/grit/test/dot_git' + '/*_/tags/_')
=> ["/home/ohnobinki/grit/test/dot_git/refs/tags/not_annotated", "/home/ohnobinki/grit/test/dot_git/refs/tags/annotated", "/home/ohnobinki/grit/test/dot_git/refs/tags/v0.7.0"]

irb(main):032:0> f = File.new('/home/ohnobinki/grit/test/dot_git/refs/tags/zebra', 'w')
=> #File:/home/ohnobinki/grit/test/dot_git/refs/tags/zebra
irb(main):033:0> files = Dir.glob('/home/ohnobinki/grit/test/dot_git' + '/*_/tags/_')
=> ["/home/ohnobinki/grit/test/dot_git/refs/tags/zebra", "/home/ohnobinki/grit/test/dot_git/refs/tags/not_annotated", "/home/ohnobinki/grit/test/dot_git/refs/tags/annotated", "/home/ohnobinki/grit/test/dot_git/refs/tags/v0.7.0"]

git's tag subcommand likes to alphabetize stuff while grit likes to trust the filesystem to maintain alphabeticality. ;-)

**Comment by technoweenie** [comment]
I'd rather just update the tests so they don't rely on any specific order.  Ruby's default sort implementation sucks when comparing lowercased and uppercased strings.

**Comment by binki** [comment]
if order doesn't matter, why are the tags returned as a list and not as a hash? (I'm not fluent in ruby, so I could be missing some convenient method for quickly getting at a particular tag object ;-))

**Comment by binki** [comment]
Anyone have any comments on http://github.com/ohnobinki/grit/commit/26769e8b13ed42d601a8cd6e2bd246a1c2cc9215 ?

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
