### ISSUE TITLE
win32 popen3

### ISSUE THREAD

**Issue by ghazel** [mojombo/grit#4]
To support Windows, a very simple bit of code can be added:

<pre>
if RUBY_PLATFORM =~ /mswin32/
  require "win32/open3"
end
</pre>

I put it at the bottom of `lib\open3_detach.rb`, but really it can go anywhere, as long as it's imported after - it overwrites `Open3.popen3`.

Users will need to install the "win32-open3" gem, which is simple.

**Comment by munishm** [comment]
does it make it work under windows? I do not see this file under lib directory not sure if i add this to any other ruby file it will work.

Also, if I try to install "win32-open3", it says it can only be done for ruby <1.9.0.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
