### ISSUE TITLE
Grit::Git#clone does not when passed option :quite => true

### ISSUE THREAD

**Issue by ghost** [mojombo/grit#46]
```
require 'grit'
require 'fileutils'

include Grit

FileUtils.mkdir_p('/tmp/test')
gritty = Grit::Git.new('/tmp/test')
gritty.clone({:quite => true, :branch => 'origin/master'}, "git://github.com/cookbooks/cc-aws.git", '/tmp/test')
Dir.entries('/tmp/test').size
# => 2

gritty.clone({:quite => false, :branch => 'origin/master'}, "git://github.com/cookbooks/cc-aws.git", '/tmp/test')
Dir.entries('/tmp/test').size
# => 10
```

Env details are:

```
$ gem list grit

*** LOCAL GEMS ***

grit (2.3.0)



$ rvm info

ruby-1.9.2-p0@test-chef:
```

  system:
    uname:       "Linux desktop 2.6.32-26-generic #48-Ubuntu SMP Wed Nov 24 10:14:11 UTC 2010 x86_64 GNU/Linux"
    bash:        "/bin/bash => GNU bash, version 4.1.5(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.0.16 by Wayne E. Seguin (wayneeseguin@gmail.com) [http://rvm.beginrescueend.com/]"

  ruby:
    interpreter:  "ruby"
    version:      "1.9.2p0"
    date:         "2010-08-18"
    platform:     "x86_64-linux"
    patchlevel:   "2010-08-18 revision 29036"
    full_version: "ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-linux]"

  homes:
    gem:          "/home/hedge/.rvm/gems/ruby-1.9.2-p0@test-chef"
    ruby:         "/home/hedge/.rvm/rubies/ruby-1.9.2-p0"

  binaries:
    ruby:         "/home/hedge/.rvm/rubies/ruby-1.9.2-p0/bin/ruby"
    irb:          "/home/hedge/.rvm/rubies/ruby-1.9.2-p0/bin/irb"
    gem:          "/home/hedge/.rvm/rubies/ruby-1.9.2-p0/bin/gem"
    rake:         "/home/hedge/.rvm/gems/ruby-1.9.2-p0@global/bin/rake"

  environment:
    PATH:         "/home/hedge/.rvm/gems/ruby-1.9.2-p0@test-chef/bin:/home/hedge/.rvm/gems/ruby-1.9.2-p0@global/bin:/home/hedge/.rvm/rubies/ruby-1.9.2-p0/bin:/home/hedge/.rvm/bin:/home/hedge/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"
    GEM_HOME:     "/home/hedge/.rvm/gems/ruby-1.9.2-p0@test-chef"
    GEM_PATH:     "/home/hedge/.rvm/gems/ruby-1.9.2-p0@test-chef:/home/hedge/.rvm/gems/ruby-1.9.2-p0@global"
    BUNDLE_PATH:  "/home/hedge/.rvm/gems/ruby-1.9.2-p0@test-chef"
    MY_RUBY_HOME: "/home/hedge/.rvm/rubies/ruby-1.9.2-p0"
    IRBRC:        "/home/hedge/.rvm/rubies/ruby-1.9.2-p0/.irbrc"
    RUBYOPT:      ""
    gemset:       "test-chef"

**Comment by rtomayko** [comment]
The command is likely failing due to `--quite` not being a valid argument to `git-clone`. Unfortunately, grit does not raise an exception when a git command exits non-zero. There's not a whole lot we can do outside of raising an exception when a git command fails (planned) or verifying option arguments against a list of possible options for each command, which nobody wants to manage.

**Comment by cookbooks** [comment]
Apologies - another monkey trying to bang out Shakespeare!
