### ISSUE TITLE
NoSuchPathError when cloning remote repo via ssh. Cloning remote also seems a little difficult.

### ISSUE THREAD

**Issue by garysweaver** [mojombo/grit#47]
When I use the following with a github read-only repository URL it works fine:

```
root_tmp = './repos'
FileUtils.mkdir_p(root_tmp)
fillin_tmp = File.join(root_tmp, 'fill-in')
clone_tmp = File.join(root_tmp, 'hourz')
begin
  fillin_tmp_g = Grit::Git.new("#{fillin_tmp}")
  fillin_tmp_g.clone({:quiet => false, :verbose => true, :progress => true, :branch => '37s'}, "https://github.com/garysweaver/hourz", "#{clone_tmp}")
  g = Grit::Repo.new("#{clone_tmp}", {:is_bare => true})
rescue Exception => e
  puts "#{e.inspect}"
end
```

However, when the uri is an ssh uri to the git repository, it asks for the password (which I type in correctly), and I get:

```
#<Grit::NoSuchPathError: /path/to/project/repos/someproject>
```

I had this issue before and it was due to a malformed url (like using the http url from GitHub vs. the Git url). The remote repo url does not end in .git. What is the best way to clone a remote remote git repo via ssh url?

Is there an easier way to clone a repository that doesn't already exist locally (fresh clone)?

Thanks for Grit! It's awesome to be able to use git via Ruby.

Gary

**Comment by garysweaver** [comment]
A workaround to clone via ssh without grit, by just calling out to git with system:

```
  repo_uri = 'ssh://user@sample.host.edu/path/to/repository'
  clone_dir = 'my_project'
  cmd = "git clone #{repo_uri} \"#{clone_dir}\""
  # can use exec cmd to debug/provide better output.
  #exec cmd
  success = system cmd
  raise "clone failed! try exec '#{cmd}' for error info" if !success
```

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
