### ISSUE TITLE
head commit inconsistency

### ISSUE THREAD

**Issue by ghazel** [mojombo/grit#5]
Even though repo.head and repo.heads.first are the same, the commit is different:

<pre>
irb(main):001:0> require 'grit'
=> true
irb(main):002:0> repo = Grit::Repo.new(".")
=> #&lt;Grit::Repo "S:/.git"&gt;
irb(main):003:0> repo.heads
=> [#&lt;Grit::Head "master"&gt;, #&lt;Grit::Head "ben"&gt;, #&lt;Grit::Head "feature1"&gt;, #&lt;Grit::Head "nokogiri"&gt;]
irb(main):004:0> repo.head
=> #&lt;Grit::Head "master"&gt;
irb(main):005:0> repo.heads.first
=> #&lt;Grit::Head "master"&gt;
irb(main):006:0> repo.head.commit
=> ""
irb(main):007:0> repo.heads.first.commit
=> #&lt;Grit::Commit "743f50dad6e5646e4e1d978998b61d3a774ba64a"&gt;
</pre>

**Comment by technoweenie** [comment]
Fixed in 0807a126972af1b7606c55b2f8e80f0888f37036
