### ISSUE TITLE
fatal: corrupt tree file

### ISSUE THREAD

**Issue by jondot** [mojombo/grit#50]
Hi all,
Im trying to use gollum as a private wiki on my windows machine. When editing and saving an existing item git tells me that the tree file is corrupt. im assuming this is something in grit and not gollum.

fatal: corrupt tree file
this is verified on Windows only.
64,32bit, winxp, win2003, ruby187, ruby192, and jruby

**Comment by technoweenie** [comment]
This happens every time you edit a page?  What are the contents of the tree?

**Comment by jondot** [comment]
yes. this is the flow to reproduce:
gem install gollum
cd wiki
git init .
gollum
-> hit localhost:4567
-> create a new page
-> edit the same page & save
i get redirected to the 'create page' page for the same page item. at this stage the tree is already corrupt.

i mention again that this all happens in Windows based environments (the ones mentioned above, not same machines necessarily).

**Comment by technoweenie** [comment]
Well, you may have to fix the bug on your end then.  What are the contents of the tree?  

```
git cat-file -p TREE_SHA
```

**Comment by jondot** [comment]
C:\wiki>git cat-file -p `f1f4bc2c8a9f31928c22e242890094c0e7e50a07`
tree `c1e3cc319766933e694784f16cdb2207dbe3d543`
parent `f7ca910c838fbe39764ba5894fb832295cd54dd2`
author jondot jondotan@gmail.com 1293806444 -0700
committer jondot jondotan@gmail.com 1293806444 -0700

**Comment by technoweenie** [comment]
That's a commit.  Run that on the tree sha.

**Comment by jondot** [comment]
C:\wiki>git cat-file -p `c1e3cc319766933e694784f16cdb2207dbe3d543`
040000 tree `fd22caff3eb4f3acb0dac3d5600b8d609cc956cf`    :
100644 blob `c69338169bf60650209c2dc610a0013f43d81f10`    Home.md

um, is it possible that it committed ':' because of the way the path looks? (c:) and its not really legal in windows?

**Comment by technoweenie** [comment]
Possibly.  That looks like a bug in `Grit::Index`

**Comment by jondot** [comment]
sorry, feels like a bug in gollum.. i'll track it down, thanks

**Comment by jondot** [comment]
confirmed. normalize_dir in gollum is not win32 safe. sorry for the hassle.
