### ISSUE TITLE
git.rev_list is incorrect for tags

### ISSUE THREAD

**Issue by pellucidity** [mojombo/grit#56]
Here is some sample output from a test repo, showing that git-rev-list will return the SHA of the 'real' commit for a tag, not the SHA of a tag node:

```
$ git rev-parse SJTag-1
e88867a8c8f085e42c092f8e9e8cc6d34ca6a898
$ git rev-list --max-count=1 SJTag-1
b6bc4884812c7489bcbb8f2750ef74f99d2441a7
$ git rev-parse master
f5f9894f71865f2141c6cebe0db878bc04d98198
$ git rev-list --max-count=1 master
f5f9894f71865f2141c6cebe0db878bc04d98198
```

Note that the SHAs are different for the tag, but not for master.

Now, if I do the same operation in a console using grit:

```
>> git
=> #<Grit::Git:0x102fe4e50 @work_tree="/src/TestGit", @git_dir="/src/TestGit/.git", @bytes_read=0>

>> git.rev_parse({},"SJTag-1")
=> "e88867a8c8f085e42c092f8e9e8cc6d34ca6a898"
>> git.rev_list({:max_count => 1},"SJTag-1")
=> "e88867a8c8f085e42c092f8e9e8cc6d34ca6a898"

>> git.rev_parse({},"master")
=> "f5f9894f71865f2141c6cebe0db878bc04d98198"
>> git.rev_list({:max_count => 1},"master")
=> "f5f9894f71865f2141c6cebe0db878bc04d98198"
```

git.rev_list appears to be wrong.

My use case for this is determining the commit represented by a ref which can be a SHA, SHA-ish, branch name, tag name, or 'master'. Tags are the tricky case as their own SHA is different from the desired commit.

Current workaround:

```
if @ref && @ref != 'master' && !(@ref =~ /\b[0-9a-f]{40}\b/i)
  real_commit_sha = repo.git.commit_from_sha(@commit.sha)
  unless real_commit_sha == @commit.sha
    @tag = @commit
    @commit = repo.commit(real_commit_sha)
  end
end
```

Tested with:
git version 1.7.3.2
git version 2.4.1 (didn't see anything related in recent commits..?)

**Comment by rtomayko** [comment]
Yeah. That's definitely not right. I'm assuming this is somewhere in the git-ruby implementation since the behavior is different from `git-rev-list`. I'm not super familiar with that code but I'll see what I can figure out.

**Comment by pellucidity** [comment]
I wrote that pretty late at night and didn't trace it. I've gone back and confirmed that repo.commits(_ref_, _options_) does call rev_list, and I can fool Grit into calling out to native by passing :format => "UTF-8" to git.rev_list (not that I really want to go down that path).

it looks like Grit::GitRuby::Repository#walk_log determines the 'real' SHA correctly but the code that follows goes awry, since adding 
    return [commit_sha] if opts[:max_count] == 1 && opts.keys.size == 1
after commit_sha is determined gets me the correct value. It has to be said that that's not really a satisfactory fix for all kinds of reasons.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
