### ISSUE TITLE
Error when trying to get commits in the empty repo

### ISSUE THREAD

**Issue by nashby** [mojombo/grit#57]
```
g = Grit::Repo.new("D:\\test-git-repo")
p g.commits
```

If `test-git-repo` is an empty repo we get this error: 
    C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/process.rb:291:in `spawn
    ': can't convert nil into String (TypeError)
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/process.rb:
    291:in`spawn'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/process.rb:
    271:in `popen4'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/process.rb:
    97:in`exec!'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/process.rb:
    68:in `initialize'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/git.rb:301:
    in`new'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/git.rb:301:
    in `native'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/git.rb:325:
    in`method_missing'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/git-ruby.rb
    :108:in `rev_parse'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/git-ruby.rb
    :64:in`rev_list'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/commit.rb:1
    21:in `find_all'
          from C:/Ruby192/lib/ruby/gems/1.9.1/gems/grit-2.4.1/lib/grit/repo.rb:365
    :in`commits'
          from D:/test.rb:4:in `<main>'`

**Comment by sawilde** [comment]
I also get this same issue whilst using bugspots - https://github.com/igrigorik/bugspots/issues/10#issuecomment-3245313 - but my repo is not empty.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
