### ISSUE TITLE
bug A log operation when there's trailing or leading white space on a file fails

### ISSUE THREAD

**Issue by dkowis** [mojombo/grit#59]
The path is not quoted or escaped when the native command is called and so a filename with a leading or trailing space is never accessible by, for example git log. Quoting or escaping the path should solve such a problem:

repo.log('master', ' filename with evil leading and trailing space.txt ') should work, but doesn't.

**Comment by dkowis** [comment]
Fixed with a pull request: https://github.com/mojombo/grit/pull/60

**Comment by bobbywilson0** [comment]
Looks like this was merged in, please close this ticket
