### ISSUE TITLE
Get remote origin from repository

### ISSUE THREAD

**Issue by garysweaver** [mojombo/grit#6]
I need to be able to get the remote origin of the git repository that you can get at command-line via "git remote show origin". It'd be nice if Grit could provide this. Is there a way in current version to do it? (Didn't see a way in the docs.)

**Comment by juanje** [comment]
I guess this is an obsolete issue and it should be closed but this is a way to get the _remote_ `origin`:

``` ruby
repo = Grit::Repo.new('path/to/the/local/repo')
origin = repo.config['remote.origin.url']
```

**Comment by garysweaver** [comment]
Thanks!
