### ISSUE TITLE
unable to unpack files stored with pack.window 0

### ISSUE THREAD

**Issue by orefalo** [mojombo/grit#63]
used 
git --config pack.window 0
to get around an issue with git on win32.

now gitorious is failing with this error when I browse the file via the web interface:

Grit::GitRuby::Internal::PackFormatError (invalid type 5):
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:272:in `unpack_object'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:299:in`unpack_deltified'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:267:in `unpack_object'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:240:in`block in parse_object'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:77:in `with_packfile'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:239:in`parse_object'
  vendor/grit/lib/grit/git-ruby/internal/pack.rb:115:in `[]'
  vendor/grit/lib/grit/git-ruby/repository.rb:79:in`block in get_raw_object_by_sha1'
  vendor/grit/lib/grit/git-ruby/repository.rb:78:in `each'
  vendor/grit/lib/grit/git-ruby/repository.rb:78:in`get_raw_object_by_sha1'
  vendor/grit/lib/grit/git-ruby/repository.rb:187:in `get_raw_tree'
  vendor/grit/lib/grit/git-ruby/repository.rb:212:in`ls_tree_path'
  vendor/grit/lib/grit/git-ruby/repository.rb:178:in `block in ls_tree'
  vendor/grit/lib/grit/git-ruby/repository.rb:177:in`each'
  vendor/grit/lib/grit/git-ruby/repository.rb:177:in `ls_tree'
  vendor/grit/lib/grit/git-ruby.rb:36:in`ls_tree'
  vendor/grit/lib/grit/tree.rb:18:in `construct'
  vendor/grit/lib/grit/repo.rb:234:in`tree'
  app/controllers/trees_controller.rb:45:in `show'
  vendor/rails/actionpack/lib/action_controller/base.rb:1331:in`perform_action'
  vendor/rails/actionpack/lib/action_controller/filters.rb:617:in `call_filters'
  vendor/rails/actionpack/lib/action_controller/filters.rb:610:in`perform_action_with_filters'
  vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `block in perform_action_with_benchmark'
  vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in`block in ms'
  /opt/ruby192/lib/ruby/1.9.1/benchmark.rb:309:in `realtime'
  vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in`ms'
  vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_with_benchmark'
  vendor/rails/actionpack/lib/action_controller/rescue.rb:160:in`perform_action_with_rescue'
  vendor/rails/actionpack/lib/action_controller/flash.rb:146:in `perform_action_with_flash'
  vendor/rails/actionpack/lib/action_controller/base.rb:532:in`process'
  vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_with_filters'
  vendor/rails/actionpack/lib/action_controller/base.rb:391:in`process'
  vendor/rails/actionpack/lib/action_controller/base.rb:386:in `call'
  vendor/rails/actionpack/lib/action_controller/routing/route_set.rb:437:in`call'
  vendor/rails/actionpack/lib/action_controller/dispatcher.rb:87:in `dispatch'
  vendor/rails/actionpack/lib/action_controller/dispatcher.rb:121:in`_call'
  vendor/rails/actionpack/lib/action_controller/dispatcher.rb:130:in `block in build_middleware_stack'
  vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in`call'
  vendor/rails/activerecord/lib/active_record/query_cache.rb:29:in `block in call'
  vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in`cache'
  vendor/rails/activerecord/lib/active_record/query_cache.rb:9:in `cache'
  vendor/rails/activerecord/lib/active_record/query_cache.rb:28:in`call'
  vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  vendor/rails/actionpack/lib/action_controller/string_coercion.rb:25:in`call'
  rack (1.0.1) lib/rack/head.rb:9:in `call'
  rack (1.0.1) lib/rack/methodoverride.rb:24:in`call'
  vendor/rails/actionpack/lib/action_controller/params_parser.rb:15:in `call'
  vendor/rails/railties/lib/rails/rack/metal.rb:47:in`call'
  vendor/rails/actionpack/lib/action_controller/session/cookie_store.rb:93:in `call'
  vendor/rails/activesupport/lib/active_support/cache/strategy/local_cache.rb:24:in`call'
  vendor/rails/actionpack/lib/action_controller/failsafe.rb:26:in `call'
  rack (1.0.1) lib/rack/lock.rb:11:in`block in call'
  internal:prelude:10:in `synchronize'
  rack (1.0.1) lib/rack/lock.rb:11:in`call'
  vendor/rails/actionpack/lib/action_controller/dispatcher.rb:106:in `call'
  passenger (3.0.5) lib/phusion_passenger/rack/request_handler.rb:96:in`process_request'
  passenger (3.0.5) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.5) lib/phusion_passenger/abstract_request_handler.rb:274:in`main_loop'
  passenger (3.0.5) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.5) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in`block in handle_spawn_application'
  passenger (3.0.5) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.5) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in`handle_spawn_application'
  passenger (3.0.5) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.5) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.5) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.5) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in`start'
  passenger (3.0.5) lib/phusion_passenger/spawn_manager.rb:219:in `block (2 levels) in spawn_rails_application'
  passenger (3.0.5) lib/phusion_passenger/abstract_server_collection.rb:132:in`lookup_or_add'
  passenger (3.0.5) lib/phusion_passenger/spawn_manager.rb:214:in `block in spawn_rails_application'
  passenger (3.0.5) lib/phusion_passenger/abstract_server_collection.rb:82:in`block in synchronize'
  internal:prelude:10:in `synchronize'
  passenger (3.0.5) lib/phusion_passenger/abstract_server_collection.rb:79:in`synchronize'
  passenger (3.0.5) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.5) lib/phusion_passenger/spawn_manager.rb:132:in`spawn_application'
  passenger (3.0.5) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.5) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.5) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.5) helper-scripts/passenger-spawn-server:99:in`<main>'

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
