### ISSUE TITLE
Grit::GitRuby::Internal::LooseObjectError - size mismatch

### ISSUE THREAD

**Issue by qichunren** [mojombo/grit#65]
In an exist git repository,  I visit http://localhost:4567, then I write a first wiki, then submit it, and I got exception below:

Grit::GitRuby::Internal::LooseObjectError - size mismatch:
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:59:in `get_raw_object'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb:32:in`[]'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:84:in `block in get_raw_object_by_sha1'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in`each'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:83:in `get_raw_object_by_sha1'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:105:in`get_object_by_sha1'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:155:in `cat_file'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby.rb:27:in`block in cat_file'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby.rb:224:in `block in try_run'
 /Users/qichunren/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/timeout.rb:57:in`timeout'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby.rb:223:in `try_run'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/git-ruby.rb:27:in`cat_file'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/grit-2.4.1/lib/grit/blob.rb:43:in `data'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/page.rb:151:in`raw_data'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/page.rb:160:in `text_data'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/markup.rb:14:in`initialize'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/page.rb:171:in `new'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/page.rb:171:in`formatted_data'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/frontend/app.rb:188:in `show_page_or_file'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/lib/gollum/frontend/app.rb:42:in`block in class:App'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1126:in `call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1126:in`block in compile!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:709:in `instance_eval'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:709:in`route_eval'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:693:in `block (2 levels) in route!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:741:in`block in process_route'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:738:in `catch'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:738:in`process_route'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:692:in `block in route!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:691:in`each'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:691:in `route!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:826:in`dispatch!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:619:in `block in call!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:791:in`instance_eval'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:791:in `block in invoke'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:791:in`catch'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:791:in `invoke'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:619:in`call!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:604:in `call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/showexceptions.rb:21:in`call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1245:in `block in call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1276:in`synchronize'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1245:in `call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.2/lib/rack/content_length.rb:13:in`call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.2/lib/rack/chunked.rb:15:in `call'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/connection.rb:84:in`block in pre_process'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/connection.rb:82:in `catch'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/connection.rb:82:in`pre_process'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/connection.rb:57:in `process'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/connection.rb:42:in`receive_data'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/backends/base.rb:61:in `start'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/thin-1.2.8/lib/thin/server.rb:159:in`start'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.2/lib/rack/handler/thin.rb:14:in `run'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.2.1/lib/sinatra/base.rb:1208:in`run!'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/gems/gollum-1.3.0/bin/gollum:125:in `<top (required)>'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/bin/gollum:19:in`load'
 /Users/qichunren/.rvm/gems/ruby-1.9.2-p0/bin/gollum:19:in `<main>'

**Comment by ralfebert** [comment]
This is already fixed in master, installing the current master branch fixes the issue:
https://github.com/mojombo/grit/commit/593f6cae465aa6d4b089cede8dc0cd8c4b5fe6cc

I also opened a ticket for gollum: https://github.com/github/gollum/issues/147

@mojombo: Could a bugfix release v2.4.2 be released for this rather nasty bug?

**Comment by lonre** [comment]
> Could a bugfix release v2.4.2 be released for this rather nasty bug?

+1

**Comment by sunny** [comment]
Experiencing the same with utf-8 chars like `é`. Would love a v2.4.2.

**Comment by directionless** [comment]
Just ran into this while dealing with text that had en-dashes in ruby 1.9. I'd love to see a fix.

**Comment by paulogeyer** [comment]
> Could a bugfix release v2.4.2 be released for this rather nasty bug?

+1

**Comment by masnick** [comment]
> Could a bugfix release v2.4.2 be released for this rather nasty bug?

+1

**Comment by javierav** [comment]
> Could a bugfix release v2.4.2 be released for this rather nasty bug?

+1

**Comment by zatmonkey** [comment]
I have the same issue here ... I use git 1.7.5.4 
any chance this gets solved ?

thanks !

**Comment by liwh** [comment]
+1

**Comment by pateketrueke** [comment]
+1

**Comment by simonc** [comment]
+1

**Comment by Sephi-Chan** [comment]
+1

**Comment by lucasmartins** [comment]
+1

**Comment by danielpuglisi** [comment]
+1

**Comment by jmay** [comment]
+2

**Comment by vkill** [comment]
+1

**Comment by antage** [comment]
+1

**Comment by punkstar** [comment]
+1

**Comment by ikaros** [comment]
+1

**Comment by ikaros** [comment]
+1

**Comment by dmitry** [comment]
:up:

**Comment by mockturtl** [comment]
+1

**Comment by shuadoc** [comment]
Master is still broken for me.  I commented the following line, rebuilt the gem, installed a local copy, and it worked. 
`#          raise LooseObjectError, "size mismatch" if content.bytesize != size`

If you just need a wiki asap and you don't care then this is the way to go.  I didn't stop to find why this check is needed, so someone please comment if this will cause major issues.

**Comment by egbertp** [comment]
I had the same error message. Fixed it by commenting line 62 of /.rvm/gems/ruby-1.9.2-p290@gollum/gems/grit-2.4.1/lib/grit/git-ruby/internal/loose.rb

Now my Gollum wiki (which uses grit) works fine! 

As @shuadoc commented above: I have no idea what I've disabled, please comment if you believe this is not the way to fix this. Thnx!

**Comment by lucasmartins** [comment]
I'm eager to try this, thanks @shuadoc & @egbertp for commenting your findings...

**Comment by dentarg** [comment]
+1

**Comment by mxswd** [comment]
+1

**Comment by mojombo** [comment]
Just pushed v2.5.0 which includes a fix for this.

**Comment by Vanuan** [comment]
I experience this issue on v2.5.0. Are you sure the fix is included? BTW, when will be a new version?

**Comment by rnkn** [comment]
Issue is unresolved with 2.5.0 on Ruby 1.9.3.

**Comment by sailxjx** [comment]
mark this
as @shuadoc said
just comment the 59th line
