### ISSUE TITLE
repo.log fails

### ISSUE THREAD

**Issue by Moisan** [mojombo/grit#73]
The "log" methods of the Grit::Repo class fails. It calls the method "log" from the Grit:Git class which doesn't exist.

**Comment by nashby** [comment]
`Grit:Git` includes `GitRuby` which has `log` method (https://github.com/mojombo/grit/blob/master/lib/grit/git-ruby/repository.rb#L285)

**Comment by Moisan** [comment]
You are right. But I still get a missing method "log" from Grit::Git in 2.4.1. The base of the error seems to come from the process.rb file : https://github.com/mojombo/grit/blob/v2.4.1/lib/grit/process.rb#L290 . I get the error `spawn': Permission denied -  /usr/local/Cellar/git  (Errno::EACCES) from this line, even when I run with sudo (I'm running git from brew on Mac OS X). Could the problem be coming from my setup?

Here is the code I use to test it.

``` ruby
require 'grit'
repo = Grit::Repo.new("/my/git/repository/folder")
repo.log()
```

**Comment by bobbywilson0** [comment]
This works fine for me on the current release and the master branch built into a gem. There is a very good chance there is a permissions problem with your environment setup. Consider closing the issue as it isolated to your system.

**Comment by Moisan** [comment]
You are right it was a permission problem. Sorry, closing.
