### ISSUE TITLE
git: 'command' is not a git command

### ISSUE THREAD

**Issue by rhaamo** [mojombo/grit#74]
After running a commit listing on a repository (linux 2.6.38 for my tests) i got this:

``` text
D, [2011-06-10T19:45:40.124701 #11551] DEBUG -- : 
D, [2011-06-10T19:50:57.074719 #11551] DEBUG -- : /usr/bin/git --git-dir=/home/marc/src/linux-2.6.38.y/.git command
D, [2011-06-10T19:50:57.156341 #11551] DEBUG -- : 
D, [2011-06-10T19:50:57.156704 #11551] DEBUG -- : git: 'command' is not a git command. See 'git --help'.
```

I've wrote a 'test' here: https://gist.github.com/1019440
And i use it with the linux 2.6.38 (linux-2.6.38.y) repository, any ideas about this problem ?

I'm using Grit 2.4.1 and ruby 1.9.2-p180.

**Comment by rhaamo** [comment]
Hm, nobody have an idea ? :(

**Comment by bobbywilson0** [comment]
I just tried your test and switched the repo to the grit repo itself since it was one I had handy. It worked fine. Have you tried executing your test with any other repos? I am also on OS X not Linux, but I am using Grit 2.4.1 and ruby 1.9.2-p180.

**Comment by rhaamo** [comment]
Yep i've used others repos, but small/normal repos works, and a very huge like the linux one fails.

**Comment by bobbywilson0** [comment]
I basically ran into the same error.

Here is my output: https://gist.github.com/1080713

**Comment by rhaamo** [comment]
Yep! That's what i got :)

**Comment by bobbywilson0** [comment]
Was it the exact same commit? Can you post your detailed output as well?

**Comment by rhaamo** [comment]
Not the same commit, https://gist.github.com/1081017, my linux repo is not updated to the latest also...

**Comment by rhaamo** [comment]
If somebody have an idea on how to debug this, i've no idea where to start.. This is really annoying :(

**Comment by bobbywilson0** [comment]
Unfortunately this bug is very deep rooted. What exactly are you trying to do? It may be easier at this point to just get the result you want another way than to try and fix the bug.

**Comment by rhaamo** [comment]
I need to get infos from commits, 10 by 10 (the test provided is extracted from my app).

**Comment by rhaamo** [comment]
Some update, i've bumped limits:

```
Grit::Git.git_timeout = 600 # 10.minutes
Grit::Git.git_max_size = 83886080 # 80.megabytes
```

And finally got:

```
D, [2011-08-10T10:58:36.997819 #25172] DEBUG -- : /usr/bin/git --git-dir=/home/marc/linux-3.0.y/.git rev-list --pretty=raw --max-count=10 --skip=2220 master
/home/marc/.rvm/gems/ruby-1.9.2-p180/gems/grit-2.4.1/lib/grit/process.rb:290:in `spawn': Cannot allocate memory - /usr/bin/git (Errno::ENOMEM)
```

I think i've got the same problem as #41, a memory leak in rev_list...
