### ISSUE TITLE
Warning about "spawn" method redefinition

### ISSUE THREAD

**Issue by microspino** [mojombo/grit#76]
How can I get rid of this warning?

`/Users/microspino/.rvm/gems/ruby-1.9.2-p180/gems/grit-2.4.1/lib/grit/process.rb:289: warning: method redefined; discarding old spawn
/Users/microspino/.rvm/gems/ruby-1.9.2-p180/gems/grit-2.4.1/lib/grit/process.rb:221: warning: previous definition of spawn was here`

Environment:
OS X 10.6
ruby-1.9.2-p180
grit-2.4.1

Code:
`#!/usr/bin/env ruby -wKU`

`require "grit"`
`repo = Grit::Repo.new("./project")`

`p repo.commits`

**Comment by ghost** [comment]
looks fixed on _master_, but there's one warning coming from the `diff-lcs` gem.

**Comment by microspino** [comment]
I can't find `lib/grit/process.rb` on master to verify the two lines of code. 
Does It mean I just need to wait for the next release? Sorry github noob here.

**Comment by leejarvis** [comment]
`Grit::Process` was removed in 12c98749256a099bde2e328b0c943dc2f5bdca7c in favour of `POSIX::Spawn::Child` so you wont find it in GitHub. These warnings shouldn't appear in the next stable release of grit

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
