### ISSUE TITLE
failing tests on HEAD

### ISSUE THREAD

**Issue by smtlaissezfaire** [mojombo/grit#8]
Four failing tests on HEAD (@ 2f1f63e):

http://gist.github.com/250716

**Comment by lenary** [comment]
not for me:

```
 lenary grit (master) 
 $ cat .git/refs/heads/master 
2f1f63e4e90f4a4722faa7c88244165423e14294
 lenary grit (master) 
 $ rake test --trace
(in /Users/same/Git/projects/grit)
** Invoke test (first_time)
** Execute test
Loaded suite /Users/same/.rvm/gems/ruby/1.8.7/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
..............................................................................................................................................................................
Finished in 8.532802 seconds.

174 tests, 390 assertions, 0 failures, 0 errors
```

i suppose that link will just stay there. meh, you know what i mean... (this commit: 2f1f63e4e90f4a4722faa7c88244165423e14294)

**Comment by rtomayko** [comment]
I get these too. I assume I just need to create a `/foo` directory and give my unprivileged user access. Ideally, these test repos would be created under `/tmp` or the project working dir though.

**Comment by smtlaissezfaire** [comment]
Here's a patch:

http://github.com/smtlaissezfaire/grit/commits/fix_tests/

**Comment by defunkt** [comment]
Merged into master.
