### ISSUE TITLE
tags method does not return but burns CPU

### ISSUE THREAD

**Issue by graaff** [mojombo/grit#87]
Grit::Repo.new(REPO).tags on our bare git repository does not return but does burns 100% CPU. Looks like this now hits a busy loop somewhere. It looks like this is not a regression since grit 2.3.0 which we used for quite a while in this project now also has the same issue, so I guess it is something specific we do in our project. Unfortunately I won't be able to send you the repository since it is a closed project.

Do you have any suggestions, or is there any information that I can provide that can help to track this down further?

**Comment by graaff** [comment]
I did some further digging here and traced the problem to Grit::GritRuby::Internal::PackStorage.find_object_in_index. For some reason that I haven't uncovered yet the "first + last / 2" expression there leads to a Rational, not an integer. From there on out things get out of hand. Changing this to mid = ((first + last) / 2).to_i fixes things.

I'd be happy to prepare a pull request for this because this seems like a safe and sane change, but I'd be happy to get feedback on it first (on you can fix it directly).

**Comment by graaff** [comment]
I've traced this to a "require 'mathn'" in a dependency of our own code.

**Comment by technoweenie** [comment]
How many tags does your project have?

```
$ git tag
$ ls .git/refs/tags
```

On Mon, Aug 15, 2011 at 5:43 AM, graaff
reply@reply.github.com
wrote:

> Grit::Repo.new(REPO).tags on our bare git repository does not return but does burns 100% CPU. Looks like this now hits a busy loop somewhere. It looks like this is not a regression since grit 2.3.0 which we used for quite a while in this project now also has the same issue, so I guess it is something specific we do in our project. Unfortunately I won't be able to send you the repository since it is a closed project.
> 
> Do you have any suggestions, or is there any information that I can provide that can help to track this down further?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/mojombo/grit/issues/87

## 

Rick Olson
http://github.com/technoweenie

**Comment by technoweenie** [comment]
Er, I didn't get the reply notifications :)

Go ahead and send the pull.  I don't know the PackStorage code base at all. 

What is that math module?

**Comment by graaff** [comment]
It's mathn.rb and it is part of the normal ruby distribution. It pulls in complex and rational number support. I'll make a pull request once I have a clean test run.

**Comment by netdata-be** [comment]
I'm having 468 tags and if I count the tags like this:

```
Grit::Repo.new('/var/lib/gitolite/repositories/ttt.git').tags.count
```

It takes up to 10 seconds before completion.
Is this normal?

I have already tried to implement the change:

 "first + last / 2" => ((first + last) / 2).to_i  

But this doesn't improve the speed.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
