### ISSUE TITLE
remote_list doesn't show newly created remotes

### ISSUE THREAD

**Issue by gorenje** [mojombo/grit#91]
This is because git#list_remote does the following:

```
def list_remotes
      remotes = []
      Dir.chdir(File.join(self.git_dir, 'refs/remotes')) do
        remotes = Dir.glob('*')
      end
      remotes
    rescue
      []
end
```

so if i do Git::Repo#remote_add and then Git::Repo#remote_list, my newly created remote does not show up since it has no refs in the remotes directory.

(remote_add just calls 'git remote add ...' and that does not create remote/refs, 'git fetch ...' does that)

**Comment by gorenje** [comment]
I'm using a workaround:

```
module Grit
  class Repo
    def remote_list
      Grit::Config.new(self).keys.collect do |keyname|
        keyname =~ /^remote[.](.*)[.]url$/ ? $1 : nil
      end.compact
    end
  end
end
```

i.e. retrieve the configuration, scan all keys for any keys that match "remote.<remote name>.url" and return the remote name.

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
