### ISSUE TITLE
Exception: undefined method `close' for nil:NilClass

### ISSUE THREAD

**Issue by franz** [mojombo/grit#93]
Hi,

I use grit 2.4.1 in a gitweb-like rails app, and i got this error recently:

```
Exception: undefined method `close' for nil:NilClass:

/usr/lib/ruby/gems/1.8/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:73:in
    `with_idx'

/usr/lib/ruby/gems/1.8/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:232:in
    `find_object'

/usr/lib/ruby/gems/1.8/gems/grit-2.4.1/lib/grit/git-ruby/internal/pack.rb:115:in
    `[]'

/usr/lib/ruby/gems/1.8/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:78:in
    `get_raw_object_by_sha1'

/usr/lib/ruby/gems/1.8/gems/grit-2.4.1/lib/grit/git-ruby/repository.rb:77:in
    `each'
```

This was (i believe) from this command:

```
@repo.git.native(:cat_file, {:raise => true, :t => true}, branch+':'+path)
```

( @repo is Grit::Repo )

The way we push new data into repositories is not git push, but rather rsync new git repo to a new directory alongside the old one, and change a symlink to the new one (the rails app operates on the symlink). I looked into grit code but it seems to me it doesn't keep any open file handles or such. Any ideas what could cause this error ?

Thanks

**Comment by bkeepers** [comment]
Grit is no longer maintained. See #183 and check out [libgit2/rugged](https://github.com/libgit2/rugged).
